server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.31.0.183:8761/eureka

spring:
  application:
    name: maryfarm-consumer-service
  rabbitmq:
    host: 172.31.0.183
    port: 5672
    username: guest
    password: guest
  # zipkin:
  #   base-url: http://172.31.0.183:9411
  #   enabled: true
  # sleuth:
  #   sampler:
  #   probability: 1.0
  data:
    mongodb:
      uri: mongodb://172.31.0.183:27017/maryfarm
      auto-index-creation: true


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
