server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.26.1.228:8761/eureka

spring:
  application:
    name: maryfarm-consumer-service
  rabbitmq:
    host: 172.26.1.228
    port: 5672
    username: guest
    password: guest
  # zipkin:
  #   base-url: http://172.26.1.228:9411
  #   enabled: true
  # sleuth:
  #   sampler:
  #   probability: 1.0
  data:
    mongodb:
      host: 172.26.1.228
      port: 27017
      authentication-database: admin
      database: maryfarm
      username: root
      password: 1234
      auto-index-creation: true


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
